export const FETCH_CAT_FACTS_STARTED = 'FETCH_CAT_FACTS_STARTED';
export const FETCH_CAT_FACTS_SUCCEEDED = 'FETCH_CAT_FACTS_SUCCEEDED';
export const FETCH_CAT_FACTS_FAILED = 'FETCH_CAT_FACTS_FAILED';
